# Generated by Django 5.2.6 on 2025-09-22 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NP', 'Not Specified')], max_length=2)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('current_medications', models.JSONField(blank=True, default=list)),
                ('medical_conditions', models.JSONField(blank=True, default=list)),
                ('emergency_summary', models.TextField(blank=True)),
                ('abha_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('consent_status', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('pending', 'Pending'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('consent_granted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('emergency', 'Emergency Medical Access'), ('break_glass', 'Break Glass Access'), ('authorized', 'Authorized Access')], max_length=20)),
                ('accessing_device_id', models.CharField(max_length=100)),
                ('accessing_user', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('emergency_reason', models.TextField()),
                ('biometric_confidence', models.FloatField()),
                ('supervisor_approval', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('data_accessed', models.JSONField(default=list)),
                ('actions_performed', models.JSONField(default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_template_encrypted', models.TextField()),
                ('template_version', models.CharField(default='1.0', max_length=10)),
                ('quality_score', models.FloatField()),
                ('extraction_algorithm', models.CharField(default='face_recognition', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_template', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('patient_register', 'Patient Registration'), ('biometric_enroll', 'Biometric Enrollment'), ('emergency_access', 'Emergency Access'), ('data_view', 'Data View'), ('data_update', 'Data Update'), ('consent_change', 'Consent Change'), ('system_login', 'System Login'), ('template_match', 'Biometric Match')], max_length=30)),
                ('event_description', models.TextField()),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('event_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emergencyaccess')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='api_auditlo_event_t_63e72a_idx'), models.Index(fields=['patient', 'timestamp'], name='api_auditlo_patient_acdd6d_idx'), models.Index(fields=['device_id', 'timestamp'], name='api_auditlo_device__b6a6a5_idx')],
            },
        ),
    ]
