# Generated by Django 6.0.1 on 2026-01-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_summary',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_conditions',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_summary_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_conditions_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
